### ISSUE TITLE
Tracking issue for 0.12 documentation.

### ISSUE THREAD

**Issue by museun** [museun/twitchchat#178]
- [x] Nice documentation in `lib.rs`.
- [x] docs.rs `#[cfg]` support.
- [x] README.md documentation
- [x] doc tests for most things
