### ISSUE TITLE
Tracking issue for 0.9

### ISSUE THREAD

**Issue by museun** [museun/twitchchat#93]
- [x] Ensure the *readme* is updated
- [x] Write more documentation for `lib.rs`
- [x] Look into `doctest` to `include_str!()` a markdown file
- [x] Re-enable rate limiter #91 
- [x] ~`send_raw` or maybe impl `AsyncWrite` for the `Writer`~
- [x] Add a (simple) bot example
- [x] More usage documentation
- [x] Extensively document some of the features
- [x] ~Maybe add some integration tests~
- [x] ~Maybe explain how to use this in a non-tokio application~
    - [x] ~using the sync stuff + crossbeam + a tokio-localset~
- [x] ~Maybe do some fuzzing of the decoder~
- [x] Make the CI .. less basic
    - [x] Test on stable
    - [x] ~Test on nightly~
    - [x] Feature matrix
        - [x] no features
        - [x] no async
        - [x] native_tls
        - [x] rustls
- [x] Rename `Dispatcher::one_time` to something less .. weird
- [x] Make a discrete iterator `decode()` instead of `impl Iterator<Item = Result<Message<'t>, ParseError>> + 't`
- [x] Rename client module to something else
